encyclopedia/urls.py
from django.urls import path

from . import views

# Add app name to differentiate multiple apps in project
app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>/', views.entry, name='entry'),
    path('search/', views.search, name='search'),
    path('new/', views.new_page, name='new_page'),
    path('edit/', views.edit_page, name='edit_page'),
    path('random/', views.random_page, name='random_page')
    ]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import redirect, render
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.contrib import messages


from . import util


def index(request):
    """
    Renders page with list of all entries,
    as a hrefs to each of them.
    """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    """
    Renders page for matching entry.
    """
    return render(request, "encyclopedia/entry.html", {
        "entry": util.get_entry(title),
        "entry_title": util.get_filename(title)
    })

def search(request):
    """
    Searches for entries matching user's input submitted
    via POST method in HTML form.
    """
    if request.method == 'POST':
        
        # Saving query from HTML form submited via POST method.
        query = request.POST['query']

        # If util.get_entry() can't find entry with name equal to query string,
        # search function is trying to find entry with name containing the query,
        # as a substring.
        if not util.get_entry(query):
            list_of_entries = util.list_similar(query)
            if not list_of_entries:
                messages.info(request, "Unfortunatelly, we couldn't find any matches.")
                return redirect('encyclopedia:index')

            else:
                messages.info(request, f"Unfortunatelly, we couldn't find exact match for query '{query}'. List of similar entries displayed below.")
                return render(request, "encyclopedia/search.html", {
                    "query": query,
                    "list_of_entries": list_of_entries
                })

        # If util.get_entry() found entry with name equal to query string,
        # search function is rendering it's page.    
        else:
            title = query
            return render(request, "encyclopedia/entry.html", {
                "entry": util.get_entry(title),
                "entry_title": util.get_filename(title)
            })

    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })

def new_page(request):
    """
    Adds submitted entry to entries/ or renders new_page.html
    with possibility to create and add one.
    """
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')

        # Checks if entry already exists.
        if util.get_filename(title) != None:
            # If yes, redirects to new_page with message,
            # that page with that name already exists.
            messages.info(request, "Entry with that title already exists. If you want to add new content or edit existing, please use 'Edit' option on that entry's page.")
            return redirect('encyclopedia:new_page')
        else:
            # If not, create new file
            # in entries/ directory
            util.save_entry(title, content)
            messages.info(request, "New entry successfully added.")
            return redirect('encyclopedia:entry', title=title)

    else:
        return render(request, "encyclopedia/new_page.html")


def edit_page(request):
    """
    Edits existing entry.
    """
    if request.method == 'POST':

        title = request.POST.get('title')
        content = request.POST.get('content')

        util.save_entry(title, content)
        
        messages.info(request, "Entry successfully edited.")
        return redirect('encyclopedia:entry', title=title)
  
    else:
        title = request.GET.get('title')
        return render(request, 'encyclopedia/edit_page.html', {
            'title': title,
            'content': util.get_entry_markdown(title),
        })

def random_page(request):
    """
    Redirects to random entry.
    """
    # Generate random selection
    random_choice = util.get_random()
    return redirect('encyclopedia:entry', title=random_choice)

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New page - Encyclopedia
{% endblock %}

{% block header %}
    EDIT PAGE
{% endblock %}

<!-- Messages -->
{% block message %}
        {% if messages %}
        <div class="col text-center alert-warning py-1 px-5">
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
{% endblock %}

{% block body %}
    <!-- Info about formating new entry -->
    <div class="row">
        <div class="col info-bar py-3 px-5">
            <h4>Writing and formatting</h4>
            <p>Please ensure that when writing content for new page, you are using Markdown. Markdown is a lightweight markup language with plain-text-formatting syntax, created in 2004 by John Gruber and Aaron Swartz. Markdown is often used for formatting readme files, for writing messages in online discussion forums, and to create rich text using a plain text editor.            </p>
            <hr>
            <p class="mb-0">For basic writing and formating guide, visit <a href="https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax">GitHub Docs</a>.</p>      
        </div>
    </div>

    <!-- Form with title and content for new entry -->
    <form action="{% url 'encyclopedia:edit_page' %}" method="POST">
        {% csrf_token %}
        <div class="row pt-3 pb-3 px-5">
            <div class="col" style="height: 40vh;">
                <input name="title" class="form-control sharp-border" type="text" id="newPageTitleInput" value="{{ title }}" hidden required>
                <label for="newPageContentInput"><h6>Type Markdown formatted content to edit page content.</h6></label>
                <textarea name="content" style="resize:none; height: 90%;" class="form-control text-field-custom sharp-border" id="newPageContentInput" required>{{ content }}</textarea>
            </div>
        </div>
        <input class="btn btn-outline-success sharp-border ml-5" type="submit" value="Save changes">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if entry_title == None %}
        Not found - Encyclopedia
    {% else %}
        {{ entry_title }} - Encyclopedia
    {% endif %}
{% endblock %}

{% block header %}
    {{ entry_title|upper }}
{% endblock %}

<!-- Messages -->
{% block message %}
    {% if messages %}
    <div class="col text-center info-bar py-1">
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block body %}

    {% if entry_title %}
    <div class="row px-5">
        <div class="col ">
            {{ entry|safe }}
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col pt-3 pb-5 ml-5">
            <form action="{% url 'encyclopedia:edit_page' %}" method="GET">
                {% csrf_token %}
                <div class="input-group mb-2">
                    <input type="text" name="title" value="{{ entry_title }}" hidden>
                    <input class="btn btn-outline-success sharp-border" type="submit" value="Edit page">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Main page - Encyclopedia
{% endblock %}

{% block header %}
    ALL PAGES
{% endblock %}

<!-- Messages -->
{% block message %}
    {% if messages %}
    <div class="col text-center alert-warning py-1">
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block body %}

    <div class="row p-5">
        {% for entry in entries %}
        <div class="col-3 pb-1">
            <li class="text-secondary"><a href="{% url 'encyclopedia:entry' entry %}"><h4 class="text-secondary">{{ entry }}</h4></a></li>
        </div>
        {% endfor %}
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
        <!-- Font awesome -->
        <script src="https://kit.fontawesome.com/45fc05582a.js" crossorigin="anonymous"></script>
        
        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com"> 
        <link href="https://fonts.googleapis.com/css2?family=Righteous&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&display=swap" rel="stylesheet">
        
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- Main Logo -->
        <div class="row border-bottom px-5">
            <div class="col pt-4 text-left logo">
                Encyclopedia
            </div>
            <div class="col-3 pt-4 pb-3">
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                        <input class="form-control" type="text" name="query" placeholder="Search...">
                    </div>
                </form>
            </div>
        </div>

        <!-- Nav bar -->
        <div class="row nav-bar py-2">
            <div class="col text-center">
                <a class="text-secondary" href="{% url 'encyclopedia:index' %}">HOME PAGE</a>
            </div>
            <div class="col text-center">
                <a class="text-secondary" href="{% url 'encyclopedia:new_page' %}">CREATE NEW PAGE</a>
            </div>
            <div class="col text-center">
                <a class="text-secondary" href="{% url 'encyclopedia:random_page' %}">RANDOM PAGE</a>
            </div>  
        </div>

        <!-- Main header -->
        <div class="row main-header text-center">
            <div class="col py-2">
                {% block header %}
                {% endblock %}
            </div>
        </div>

        <!-- Message bar -->
        <div class="row">
                {% block message %}
                {% endblock %}
        </div>
        
        <!-- Content -->      
        {% block body %}
        {% endblock %}

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New page - Encyclopedia
{% endblock %}

{% block header %}
    ADD NEW PAGE
{% endblock %}

{% block message %}
        {% if messages %}
        <div class="col text-center alert-warning py-1 px-5">
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
{% endblock %}

{% block body %}
    <!-- Info about formating new entry -->
    <div class="row">
        <div class="col info-bar py-3 px-5">
            <h4>Writing and formatting</h4>
            <p>Please ensure that when writing content for new page, you are using Markdown. Markdown is a lightweight markup language with plain-text-formatting syntax, created in 2004 by John Gruber and Aaron Swartz. Markdown is often used for formatting readme files, for writing messages in online discussion forums, and to create rich text using a plain text editor.            </p>
            <hr>
            <p class="mb-0">For basic writing and formating guide, visit <a href="https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax">GitHub Docs</a>.</p>      
        </div>
    </div>

    <!-- Form with title and content for new entry -->
    <form action="{% url 'encyclopedia:new_page' %}" method="POST">
        {% csrf_token %}
        <div class="row pt-3 px-5">
            <div class="col">
                <label for="newPageTitleInput"><h6>Type title for new page below.</h6></label>
                <input name="title" class="form-control sharp-border" type="text" id="newPageTitleInput" required>
            </div>
        </div>
        <div class="row pt-3 pb-3 px-5">
            <div class="col" style="height: 40vh;">
                <label for="newPageContentInput"><h6>Type Markdown formatted content for new page below.</h6></label>
                <textarea name="content" style="resize:none; height: 90%;" class="form-control text-field-custom sharp-border" id="newPageContentInput" required></textarea>
            </div>
        </div>
        <input class="btn btn-outline-success sharp-border ml-5" type="submit" value="Add new page">
    </form>
    

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search - Encyclopedia
{% endblock %}

{% block header %}
    SEARCH RESULTS
{% endblock %}

<!-- Messages -->
{% block message %}
        {% if messages %}
        <div class="col text-center info-bar py-1">
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
{% endblock %}

{% block body %}

    {% if list_of_entries %}
    <div class="row p-5">
    
        {% for entry in list_of_entries %}
        <div class="col-3 pb-1">
            <li class="text-secondary"><a href="{% url 'encyclopedia:entry' entry %}"><h4 class="text-secondary">{{ entry }}</h4></a></li>
        </div>
        {% endfor %}
    
    </div>
    {% else %}
    Unfortunatelly, we couldn't find any matches.
    <br>You can add new entry here.
    {% endif %}

    

{% endblock %}